### ISSUE TITLE
Mute Mixin related errors from env

### ISSUE THREAD

**Issue by Faouzijedidi1** [Hu-Fi/Mr.Market#210]
## Description
- Add an env variable to be able to mute all errors coming from Mixin services.

## Motivation and Context
- Some of the users will be running Mr.Market without the Mixin side
- If the Mixin env variable are not configured the server spams errors non stop.

## Implementation

- Stop Mixin Crons when the mute variable is set to true.

**Comment by zed-wong** [comment]
Currently if we have these for `server/.env`
```
RUN_STARTEGY_FOR_MIXIN_ORDERS=false
RUN_REBALANCE=false
```
If these are applied, there will be no cron job working. The only error message will be:
```
[Nest] 33184  - 07/10/2024, 10:36:30 PM   ERROR [ExchangeService] No API Keys loaded
[Nest] 33184  - 07/10/2024, 10:36:30 PM   ERROR [ExchangeService] undefined
```
Which is one-time and doesn't have any side effects.

But maybe we can remove these vars and add a 'RUN_PURE_MARKET_MAKING' to make everything more smooth. Disable anything that's not for pure mm.
