### ISSUE TITLE
Create an example solidity contract which launches market making contract

### ISSUE THREAD

**Issue by posix4e** [Hu-Fi/Mr.Market#65]

**Comment by piotrswierzy** [comment]
@posix4e 
Regarding this task, should we simply create a factory contract that replicates the flow outlined in this script?
[link to the script](https://github.com/Hu-Fi/Mr.Market/blob/main/scripts/campaign_launcher.ts)

**Comment by posix4e** [comment]
Please work with @leric7 hea already started

**Comment by leric7** [comment]
Smart contract work is done. https://github.com/Hu-Fi/human-usd
