### ISSUE TITLE
Add market page filtering

### ISSUE THREAD

**Issue by zed-wong** [Hu-Fi/Mr.Market#73]

**Comment by zed-wong** [comment]
In /home page and /market/token page. the filtering is still a placeholder for now. we need to implement a way filter these tokens that get from coingecko market api.

**Comment by silkshjasuwienas** [comment]
@zed-wong 
Do we have any mockups presenting how this filter should look like? My current proposal is based on the tabular view of currently displayed tabs, but perhaps you would prefer a select, checkboxes, radio?

![Screenshot 2024-04-02 at 08 28 23](https://github.com/Hu-Fi/Mr.Market/assets/42935875/8e44f63d-cbd4-4235-a4f9-0c163fc85699)

**Comment by zed-wong** [comment]
> @zed-wong Do we have any mockups presenting how this filter should look like? My current proposal is based on the tabular view of currently displayed tabs, but perhaps you would prefer a select, checkboxes, radio?
> 
> ![Screenshot 2024-04-02 at 08 28 23](https://private-user-images.githubusercontent.com/42935875/318668087-8e44f63d-cbd4-4235-a4f9-0c163fc85699.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNDE4MzcsIm5iZiI6MTcxMjA0MTUzNywicGF0aCI6Ii80MjkzNTg3NS8zMTg2NjgwODctOGU0NGY2M2QtY2JkNC00MjM1LWE0ZjktMGMxNjNmYzg1Njk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA3MDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlNTU1Mjg3MDVkMjI3MTc1ODE3MDY3Zjc5MjkzZGZjNDNmOGNkNGMxOTc0YjMxOWFmOTFiMTY2NzMyNzIxMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7s5KaSHvsZk733Z3F7f8JivZWxTMlD2u5xxZyWKTlck)

Actually the first line of the filter is not implemented, we just need to implement the first line. like filter the tokens by `Mainstream`, `layer1` and so on. We don't need a second filter.

**Comment by silkshjasuwienas** [comment]
@zed-wong 
There is one issue
https://github.com/samuraitruong/coingecko-api-v3/blob/main/src/CoinGeckoClient.ts#L230
seems to support defi and stable coin categories only.

What approach should we consider? Writing our own client? Ignoring types and see what happens? Preparing pull request for this coingecko module? Or creating our fork from it?

**Comment by zed-wong** [comment]
> @zed-wong There is one issue https://github.com/samuraitruong/coingecko-api-v3/blob/main/src/CoinGeckoClient.ts#L230 seems to support defi and stable coin categories only.
> 
> What approach should we consider? Writing our own client? Ignoring types and see what happens? Preparing pull request for this coingecko module? Or creating our fork from it?

@silkshjasuwienas Sorry for the delay, I think we can try ignoring types first, if it doesn't work we can write a custom `coinMarkets` function. And if it still doesn't work, we can hardcode a list of tokens for each type and filter based on that.

**Comment by piotrswierzy** [comment]
Done.
Time spent: 3 hours 
Merged PR: https://github.com/Hu-Fi/Mr.Market/pull/117

**Comment by ansaqib** [comment]
Thanks @piotrswierzy

**Comment by ansaqib** [comment]
@zed-wong - Please review
