### ISSUE TITLE
Format orderbook decimals

### ISSUE THREAD

**Issue by zed-wong** [Hu-Fi/Mr.Market#83]

**Comment by zed-wong** [comment]
Also, based on the observation, sometimes the `amount` would be shown as 0 when the value is < 0.0001. we need to avoid this and handle it in function `formatOrderBookAmount()`

![Image](https://github.com/Hu-Fi/Mr.Market/assets/36271125/3e17aad8-e2a4-438b-b577-678c2fb4f412)

**Comment by piotrswierzy** [comment]
Done.
Time spent: 2 hours 
Merged PR: https://github.com/Hu-Fi/Mr.Market/pull/114
